//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeALLNav.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoCar
    {
        public int id { get; set; }
        public string NoCar { get; set; }
        public string Marque { get; set; }
        public string Model { get; set; }
        public int No_Societe { get; set; }
        public int Capacity { get; set; }
        public string Cilma { get; set; }
        public string Available { get; set; }
    
        public virtual Societe Societe { get; set; }
    }
}
