//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeALLNav.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line_Demande
    {
        public int Id_line_Cmd { get; set; }
        public int Id_demand_Navette { get; set; }
        public int Nbr_Demande { get; set; }
    
        public virtual Demande_Navette_Clt Demande_Navette_Clt { get; set; }
    }
}
