//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeALLNav.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line_Offre
    {
        public int Id_Offre { get; set; }
        public int Id_Navette { get; set; }
        public int Id_Ste { get; set; }
        public System.DateTime Date_Debut_Offre { get; set; }
        public System.DateTime Date_fin_Offre { get; set; }
        public double Taux_Offre { get; set; }
    
        public virtual Navette Navette { get; set; }
        public virtual Societe Societe { get; set; }
    }
}
