//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeALLNav.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeALLNEntities2 : DbContext
    {
        public WeALLNEntities2()
            : base("name=WeALLNEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoCar> AutoCar { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Demande_Navette_Clt> Demande_Navette_Clt { get; set; }
        public virtual DbSet<Line_Demande> Line_Demande { get; set; }
        public virtual DbSet<Line_Offre> Line_Offre { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Navette> Navette { get; set; }
        public virtual DbSet<Societe> Societe { get; set; }
    }
}
